---
docker-build-svc:
  image: docker:latest
  stage: build
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - |
    image=${CI_REGISTRY_IMAGE}-svc
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      tag=""
      echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
    else
      tag=":$CI_COMMIT_REF_SLUG"
      echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
    fi
  - docker build --file cyclotron-svc/Dockerfile --pull -t "${image}${tag}" cyclotron-svc
  - docker push "${image}${tag}"
  rules:
  - if: "$CI_COMMIT_BRANCH"
    exists:
    - cyclotron-svc/Dockerfile

docker-build-site:
  image: docker:latest
  stage: build
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - |
    image=${CI_REGISTRY_IMAGE}-site
    if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
      tag=""
      echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
    else
      tag=":$CI_COMMIT_REF_SLUG"
      echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
    fi
  - docker build --file cyclotron-site/Dockerfile --pull -t "${image}${tag}" cyclotron-site
  - docker push "${image}${tag}"
  rules:
  - if: "$CI_COMMIT_BRANCH"
    exists:
    - cyclotron-svc/Dockerfile

